networks:
  default:
    external:
       name: docker-server
services:
  h2o:
    build: ./testdata/h2o
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Using Volumes here instead of COPYing in the Dockerfile allows us to make changes to configuration files and/or
    # certs without needing to re-build the container image
    volumes: 
      - type: bind
        source: ./testdata/h2o/connect.conf
        target: /etc/h2o/connect.conf

      - type: bind
        source: ./testdata/h2o/server.key
        target: /etc/h2o/server.key

      - type: bind
        source: ./testdata/h2o/server.crt
        target: /etc/h2o/server.crt